### ISSUE TITLE
按照.md文件 配置了下  iOS端 debug下 还是会出错

### ISSUE THREAD

**Issue by 0xMorty9** [xiekw2010/react-native-gitfeed#1]
[tid:com.facebook.React.RCTWebSocketModuleQueue][RCTModuleMethod.m:453] RCTWebSocketModule.connect was called with 4 arguments, but expects 2

2016-03-01 16:06:55.939 [warn][tid:com.facebook.React.JavaScript] `View` has no propType for native prop `RCTView.maxHeight` of native type `CGFloat`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
这个是什么原因造成呢

**Comment by xiekw2010** [comment]
重启一下chrome，你可能开了几个chrome的调试进程。保持一个就行了。

**Comment by 0xMorty9** [comment]
```
        版本库换到了0.20就没问题了。不过一直说lightGray这个颜色保存。全局改成了别的颜色。debug就通过了发自网易邮箱大师
        在2016年03月02日 10:07，David Tse 写道:重启一下chrome，你可能开了几个chrome的调试进程。保持一个就行了。
```
