### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by DexSinis** [xiekw2010/react-native-gitfeed#6]
~/Documents/XcodeWP/GitHub/react-native-gitfeed/node_modules/react-native/packager ~
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/a000/Documents/XcodeWP/GitHub/react-native-gitfeed 

[8:34:02 PM] <START> Building Dependency Graph
[8:34:02 PM] <START> Crawling File System
[8:34:02 PM] <START> Loading bundles layout
[8:34:02 PM] <END>   Loading bundles layout (1ms)
[Hot Module Replacement] Server listening on /hot

React packager ready.

[8:34:03 PM] <END>   Crawling File System (1571ms)
[8:34:03 PM] <START> Building in-memory fs for JavaScript
[8:34:07 PM] <END>   Building in-memory fs for JavaScript (3977ms)
[8:34:07 PM] <START> Building in-memory fs for Assets
[8:34:10 PM] <END>   Building in-memory fs for Assets (2248ms)
[8:34:10 PM] <START> Building Haste Map
[8:34:12 PM] <START> Building (deprecated) Asset Map
[8:34:12 PM] <END>   Building (deprecated) Asset Map (808ms)
[8:34:12 PM] <END>   Building Haste Map (2833ms)
[8:34:12 PM] <END>   Building Dependency Graph (10635ms)

release测试的时候 一直在第一个页面转菊花，登陆不上去

**Comment by xiekw2010** [comment]
有具体的错误么或者可以提供一下具体的操作步骤么

**Comment by DexSinis** [comment]
2682  mkdir ReactNative
 2683  cd R
 2684  cd ReactNative
 2685  git clone https://github.com/xiekw2010/react-native-gitfeed
 2686  cd react-native-gitfeed
 2687  ls
 2688  npm install
 2689  sudo chown -R $(whoami) "$HOME/.npm"
 2690  npm install
 2691  cd ios
 2692  pod install
 2693  ls
 2694  open RN_CNNode.xcworkspace

打开后调试到release模式下 run 然后运行到模拟器上面，但是随便填写一个账号后出现 network require failed

这是我运行你工程的基本命令，请问哪一步出了问题还是做少了什么东西

➜  react-native-gitfeed git:(master) ✗ npm install

> RN_CNNode@0.0.1 postinstall /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed
> npm run clean:babelrc
> 
> RN_CNNode@0.0.1 clean:babelrc /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed
> find ./node_modules -name react-packager -prune -o -name '.babelrc' -print | xargs rm -f

npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/babel-polyfill/node_modules/babel-runtime requires core-js@'^1.0.0' but will load
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/babel-polyfill/node_modules/core-js,
npm WARN unmet dependency which is version 2.1.3
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel requires babel-core@'^5.6.21' but will load
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/babel-core,
npm WARN unmet dependency which is version 6.6.4
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel requires source-map@'^0.5.0' but will load
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/source-map,
npm WARN unmet dependency which is version 0.4.4
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/regenerator/node_modules/defs/node_modules/yargs/node_modules/cliui requires wordwrap@'0.0.2' but will load
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/wordwrap,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/yeoman-generator/node_modules/download/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/micromatch/node_modules/braces/node_modules/expand-range/node_modules/fill-range/node_modules/randomatic requires kind-of@'^2.0.1' but will load
npm WARN unmet dependency /Users/a000/Documents/XcodeWP/GitHub/ReactNative/react-native-gitfeed/node_modules/react-native/node_modules/yeoman-generator/node_modules/download/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/micromatch/node_modules/kind-of,
npm WARN unmet dependency which is version 3.0.2

**Comment by xiekw2010** [comment]
@DexSinis 你的步骤没什么问题。network require failed说明这个项目跑起来啊，可能你的网络出问题了？
